<a href="https://colab.research.google.com/github/MarinaWolters/Coding-Tracker/blob/master/Hands_on2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
# For string similarity
!pip3 install py_stringsimjoin

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting py_stringsimjoin
  Downloading py_stringsimjoin-0.3.2.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 11.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: joblib in /usr/local/lib/python3.8/dist-packages (from py_stringsimjoin) (1.2.0)
Requirement already satisfied: pandas>=0.16.0 in /usr/local/lib/python3.8/dist-packages (from py_stringsimjoin) (1.3.5)
Collecting PyPrind>=2.9.3
  Downloading PyPrind-2.11.3-py2.py3-none-any.whl (8.4 kB)
Collecting py_stringmatching>=0.2.1
  Downloading py_stringmatching-0.4.2.tar.gz (661 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 661.8/661.8 KB 11.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from py_stringsimjoin) (1.15.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.16.0->py_stringsimjoin) (2022.7)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.16.0->py_stringsimjoin) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.16.0->py_stringsimjoin) (2.8.2)
Building wheels for collected packages: py_stringsimjoin, py_stringmatching
  Building wheel for py_stringsimjoin (setup.py) ... done
  Created wheel for py_stringsimjoin: filename=py_stringsimjoin-0.3.2-cp38-cp38-linux_x86_64.whl size=5071180 sha256=98ee342698e28ef28b22c9ed6dcd8a6037d4ce85d004fef0d0ee208ef47de0ad
  Stored in directory: /root/.cache/pip/wheels/7f/61/96/0aa1d87a2d0a9329ea415ffaf74c875c9344434844177f2b62
  Building wheel for py_stringmatching (setup.py) ... done
  Created wheel for py_stringmatching: filename=py_stringmatching-0.4.2-cp38-cp38-linux_x86_64.whl size=2692256 sha256=31a6e6a750f9c7499d36927d8d3e6686b564739306cf1e824942c5da3c827c45
  Stored in directory: /root/.cache/pip/wheels/6d/01/57/0131e0a87fa6471ec265bd9777de2e789a4bd1248c279fa875
Successfully built py_stringsimjoin py_stringmatching
Installing collected packages: PyPrind, py_stringmatching, py_stringsimjoin
Successfully installed PyPrind-2.11.3 py_stringmatching-0.4.2 py_stringsimjoin-0.3.2



```
# This is formatted as code
```

# 1 Load data in csv format into pandas dataframe
***Excercise 1***: Load csv data files from the links below into pandas dataframe bn_books_df and am_books_df.
http://pages.cs.wisc.edu/~anhai/data/784_data/books4/csv_files/barnes_and_noble.csv
http://pages.cs.wisc.edu/~anhai/data/784_data/books4/csv_files/amazon.csv

In [ ]:
bn_books_df = pd.read_csv('http://pages.cs.wisc.edu/~anhai/data/784_data/books4/csv_files/barnes_and_noble.csv')
bn_books_df

,ID,Title,Author,Hardcover,Paperback,NOOK_Book,Audiobook,ISBN_13_DUMMY,ISBN_13,Series,Publisher,Publication_Date,Sales_rank,Pages,Product_dimensions
0,0,A Guide to the Project Management Body of Know...,Project Management Institute,NaN,$38.17,NaN,NaN,9.781940e+12,978-1935589679,NaN,Project Management Institute,NaN,332,589.0,10.86(w) x 8.26(h) x 1.24(d)
1,1,Windows 10: The Missing Manual,David Pogue,NaN,$23.41,$19.99,NaN,9.781490e+12,978-1491947173,NaN,"O'Reilly Media, Incorporated",NaN,300,696.0,7.00(w) x 9.20(h) x 1.40(d)
2,2,"The Phoenix Project: A Novel about IT, DevOps,...",Gene Kim# Kevin Behr# George Spafford,,$13.17,$9.99,NaN,9.780990e+12,978-0988262508,NaN,IT Revolution Press,NaN,"30,046",376.0,5.90(w) x 8.90(h) x 1.10(d)
3,3,Reclaiming Conversation: The Power of Talk in ...,Sherry Turkle,$17.46,NaN,$14.99,$31.83,9.781590e+12,978-1594205552,NaN,Penguin Publishing Group,NaN,238,448.0,NaN
4,4,A Work in Progress,Connor Franta,NaN,$12.17,$12.99,NaN,9.781480e+12,978-1476791616,NaN,Atria/Keywords Press,NaN,266,224.0,5.40(w) x 8.30(h) x 0.80(d)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9953,9995,Articles Into Videos,Anonymous,NaN,NaN,NaN,NaN,2.940010e+12,294-0012362599,NaN,qasim idrees,NaN,"1,270,409",NaN,NaN
9954,9996,Red Hot Internet Publicity,Penny C. Sansevieri,NaN,$18.99,$10.49,NaN,9.781610e+12,978-1605207247,NaN,Cosimo,NaN,"1,270,407",320.0,5.50(w) x 8.50(h) x 0.72(d)
9955,9997,Creative Optical & Digital Filter Techniques,Joseph R. Meehan,NaN,NaN,NaN,NaN,9.781600e+12,978-1600595806,Lark Photography Book Series,Lark Books NC,NaN,"1,270,082",160.0,8.30(w) x 10.90(h) x 0.60(d)
9956,9998,Blog Business,Mark Twain,NaN,NaN,NaN,NaN,2.940150e+12,294-0151569019,NaN,law payne,NaN,"1,269,938",NaN,NaN
9957,9999,Beginning Sensor Networks with Arduino and Ras...,Charles Bell,NaN,$39.99,$23.99,NaN,9.781430e+12,978-1430258247,NaN,Apress,NaN,NaN,372.0,9.60(w) x 11.80(h) x 1.10(d)

In [ ]:
am_books_df = pd.read_csv('http://pages.cs.wisc.edu/~anhai/data/784_data/books4/csv_files/amazon.csv')
am_books_df

,ID,Title,Author,Price,Edition,ASIN,ISBN_13,ISBN_10,Paperback,Series,...,Publication_Date,Sold_by,Language,Product Dimensions,Shipping Weight,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,1,Steve Jobs: A Biography,Walter Isaacson,$29.00,NaN,NaN,978-0002160636,2160633,NaN,NaN,...,NaN,NaN,Chinese,8.6 x 6.1 x 2.1 inches,2.7 pounds,NaN,NaN,NaN,NaN,NaN
1,2,Introduction to Control System Technology,Robert N. Bateson,$10.00,4th Edition,NaN,978-0023064630,23064633,NaN,NaN,...,NaN,NaN,English,1.2 x 7.5 x 9 inches,3 pounds,NaN,NaN,NaN,NaN,NaN
2,3,Computer Assisted Structural Analysis and Mode...,Marc Ira Hoit,$20.64,1st Edition,NaN,978-0023559723,23559721,NaN,NaN,...,NaN,NaN,English,1 x 7.8 x 9.8 inches,2 pounds,NaN,NaN,NaN,NaN,NaN
3,4,Computer Numerical Control Programming of Mach...,Larry D. Horath,$0.20 - $141.40,1st Edition,NaN,978-0023572012,23572019,268 pages,NaN,...,NaN,NaN,English,6.4 x 0.7 x 9.5 inches,14.6 ounces (View shipping rates and policies),NaN,NaN,NaN,NaN,NaN
4,5,Pascal Programming and Problem Solving,Sanford Leestma# Larry Nyhoff,$24.98 - $186.80,4th Edition,NaN,978-0023887314,23887311,969 pages,NaN,...,NaN,NaN,English,6.8 x 2 x 9.9 inches,3.4 pounds (View shipping rates and policies),NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8634,8654,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8635,8655,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8636,8656,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8637,8657,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8638,8658,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 2 Record Linking

Suppose we want to compare prices, between Barnes and Noble and Amazon.

How do we best link what's in these tables, to do the comparison?

## 2.1. Join based on ISBN-13.

***Exercise 2***: Take `bn_books_df` and `am_books_df` and join them together based on the column `ISBN_13`. If you like, you can **project** both tables to a subset of the columns.

In [ ]:
# TODO
bn_cols = ['Title', 'Author', 'Paperback', 'ISBN_13']
am_cols = ['Title', 'Author', 'Price', 'ISBN_13']
bn_books_df[bn_cols].merge(am_books_df[am_cols], on = 'ISBN_13')

,Title_x,Author_x,Paperback,ISBN_13,Title_y,Author_y,Price
0,The Shallows: What the Internet Is Doing to Ou...,Nicholas Carr,$9.72,978-0393339758,The Shallows: What the Internet Is Doing to Ou...,Nicholas Carr,$8.73
1,CISSP (ISC)2 Certified Information Systems Sec...,James M. Stewart# Mike Chapple# Darril Gibson,$40.12,978-1119042716,CISSP,James M. Stewart# Mike Chapple# James M. Stewa...,$36.49
2,Getting to Know ArcGIS for Desktop / Edition 3,Michael Law# Amy Collins,$50.31,978-1589483088,Getting to Know ArcGIS for Desktop,Michael Law# Amy Collins,$22.99 - $50.81
3,My iPhone for Seniors (Covers iOS 8 for iPhone...,Brad Miser,$17.91,978-0789753618,My iPhone for Seniors,Brad Miser,$11.49
4,Excel 2013 All-in-One For Dummies,Greg Harvey,$20.79,978-1118510100,Excel 2013 All-in-One For Dummies,Greg Harvey,$18.39
...,...,...,...,...,...,...,...
487,Practical Computer Vision with SimpleCV: The S...,Kurt Demaagd# Anthony Oliver# Nathan Oostendor...,$24.99,978-1449320362,Practical Computer Vision with SimpleCV: The S...,Kurt Demaagd# Anthony Oliver# Nathan Oostendor...,$9.99
488,Human-Computer Interaction: An Empirical Resea...,I. Scott MacKenzie,$45.00,978-0124058651,Human-Computer Interaction: An Empirical Resea...,I. Scott MacKenzie,$25.83
489,Developing WMI Solutions: A Guide to Windows M...,Craig Tunstall# Gwyn Cole# Robert L. McDonald,$35.26,978-0201616132,Developing WMI Solutions: A Guide to Windows M...,Craig Tunstall# Gwyn Cole,$29.95 - $35.26
490,Essential SharePoint 2007: A Practical Guide f...,Jeff Webb,$39.99,978-0596514075,Essential SharePoint 2007: A Practical Guide f...,Jeff Webb,$17.27
491,Beginning Sensor Networks with Arduino and Ras...,Charles Bell,$39.99,978-1430258247,Beginning Sensor Networks with Arduino and Ras...,Charles Bell,$17.27

## 2.2. Join based on Title.

***Excercise 3***: Now join `bn_books_df` and `am_books_df` on Title

In [ ]:
# TODO
bn_books_df[bn_cols].merge(am_books_df[am_cols], on = 'Title')

,Title,Author_x,Paperback,ISBN_13_x,Author_y,Price,ISBN_13_y
0,Steve Jobs,Walter Isaacson,$12.27,978-1451648546,Walter Isaacson,$13.90,NaN
1,Steve Jobs,W. Isaacson# Walter Isaacson,$25.04,978-2253168522,Walter Isaacson,$13.90,NaN
2,"CISSP All-in-One Exam Guide, 6th Edition",Shon Harris,NaN,978-0071781732,Shon Harris,$36.82,978-0071781749
3,Becoming Steve Jobs: The Evolution of a Reckle...,Brent Schlender# Rick Tetzeli,,978-0385347402,Brent Schlender# Rick Tetzeli,$22.23,NaN
4,"Future Crimes: Everything Is Connected, Everyo...",Marc Goodman,NaN,978-0385539005,Marc Goodman,$12.99,NaN
...,...,...,...,...,...,...,...
778,Practical Computer Vision with SimpleCV: The S...,Kurt Demaagd# Anthony Oliver# Nathan Oostendor...,$24.99,978-1449320362,Kurt Demaagd# Anthony Oliver# Nathan Oostendor...,$9.99,978-1449320362
779,Human-Computer Interaction: An Empirical Resea...,I. Scott MacKenzie,$45.00,978-0124058651,I. Scott MacKenzie,$25.83,978-0124058651
780,Developing WMI Solutions: A Guide to Windows M...,Craig Tunstall# Gwyn Cole# Robert L. McDonald,$35.26,978-0201616132,Craig Tunstall# Gwyn Cole,$29.95 - $35.26,978-0201616132
781,Essential SharePoint 2007: A Practical Guide f...,Jeff Webb,$39.99,978-0596514075,Jeff Webb,$17.27,978-0596514075
782,Kinect Open Source Programming Secrets: Hackin...,Andrew Davison,$25.23,978-0071783170,Andrew Davison,$25.17,NaN

## 2.3 Title and Author

***Excercise 4***: Join `bn_books_df` and `am_books_df` on Title and Author

In [ ]:
# TODO
bn_books_df[bn_cols].merge(am_books_df[am_cols], on = ['Title','Author'])

,Title,Author,Paperback,ISBN_13_x,Price,ISBN_13_y
0,Steve Jobs,Walter Isaacson,$12.27,978-1451648546,$13.90,NaN
1,"CISSP All-in-One Exam Guide, 6th Edition",Shon Harris,NaN,978-0071781732,$36.82,978-0071781749
2,Becoming Steve Jobs: The Evolution of a Reckle...,Brent Schlender# Rick Tetzeli,,978-0385347402,$22.23,NaN
3,"Future Crimes: Everything Is Connected, Everyo...",Marc Goodman,NaN,978-0385539005,$12.99,NaN
4,JavaScript and HTML5 Now,Kyle Simpson,NaN,978-1449339067,$0.00,NaN
...,...,...,...,...,...,...
543,Social Networking for Career Success: Using On...,Miriam Salpeter,,978-1576859018,$0.79,978-1576857823
544,Practical Computer Vision with SimpleCV: The S...,Kurt Demaagd# Anthony Oliver# Nathan Oostendor...,$24.99,978-1449320362,$9.99,978-1449320362
545,Human-Computer Interaction: An Empirical Resea...,I. Scott MacKenzie,$45.00,978-0124058651,$25.83,978-0124058651
546,Essential SharePoint 2007: A Practical Guide f...,Jeff Webb,$39.99,978-0596514075,$17.27,978-0596514075
547,Kinect Open Source Programming Secrets: Hackin...,Andrew Davison,$25.23,978-0071783170,$25.17,NaN

# 3 Approximate Match

Here is the setup for *Jaccard Join*, which is really two things:

1. Take each field that is to be joined and create a set of n-grams (aka q-grams).
1. Compute the Cartesian product of all items, and assign a score based on Jaccard similarity (|set intersection| / |set union|).

In [ ]:
# Approximate string matching, see 
import py_stringsimjoin as ssj
import py_stringmatching as sm


# We are going to match the strings approximately, via "n-grams" or "q-grams" (sequences of n or q characters)
# Here it's five-grams

tok = sm.QgramTokenizer(qval=3,return_set=True)

Find a good threshold here that seems to produce reasonable results.

In [ ]:
# Now let's do a similarity join

output_pairs = ssj.jaccard_join(bn_books_df[['ISBN_13','Title','Author','Paperback']].reset_index(), am_books_df[['ISBN_13','Title','Author','Price']].reset_index(), \
                                'index', 'index', 'Title', 'Title', tok, 0.1, 
                                l_out_attrs=['Title','Author','Paperback'], r_out_attrs=['Title','Author','Price'])


display(output_pairs)

output_pairs.loc[output_pairs['_sim_score'] < 1.0]

/usr/local/lib/python3.8/dist-packages/py_stringsimjoin/utils/generic_helper.py:76: FutureWarning: In a future version of pandas all arguments of DataFrame.dropna will be keyword-only
  projected_dataframe = dataframe[proj_attrs].dropna(0,
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:01:06

,_id,l_index,r_index,l_Title,l_Author,l_Paperback,r_Title,r_Author,r_Price,_sim_score
0,0,12,0,Steve Jobs,Walter Isaacson,$12.27,Steve Jobs: A Biography,Walter Isaacson,$29.00,0.370370
1,1,23,0,Becoming Steve Jobs: The Evolution of a Reckless Upstart into a Visionary Leader,Brent Schlender# Rick Tetzeli,,Steve Jobs: A Biography,Walter Isaacson,$29.00,0.105263
2,2,170,0,Steve Jobs,W. Isaacson# Walter Isaacson,$25.04,Steve Jobs: A Biography,Walter Isaacson,$29.00,0.370370
3,3,360,0,The Ultimate Field Guide to Photography,National Geographic,NaN,Steve Jobs: A Biography,Walter Isaacson,$29.00,0.118644
4,4,457,0,Digital Photography: A Basic Manual,Henry Horenstein,$21.46,Steve Jobs: A Biography,Walter Isaacson,$29.00,0.148148
...,...,...,...,...,...,...,...,...,...,...
2196369,2196369,8581,8509,The Best Free Ebook,Alan Smith,NaN,The BlackHat Way,Frederic Haddad,$4.99,0.142857
2196370,2196370,8713,8509,Black Hat SEO For Beginners,Lou Diamond,NaN,The BlackHat Way,Frederic Haddad,$4.99,0.116279
2196371,2196371,9001,8509,The Affliliate Marketing Blueprint,Brandon Olson,NaN,The BlackHat Way,Frederic Haddad,$4.99,0.100000
2196372,2196372,9681,8509,The Boost C++ Libraries,Boris Schäling,,The BlackHat Way,Frederic Haddad,$4.99,0.128205
2196373,2196373,9786,8509,The Watson Dynasty,Richard S. Tedlow,,The BlackHat Way,Frederic Haddad,$4.99,0.147059

,_id,l_index,r_index,l_Title,l_Author,l_Paperback,r_Title,r_Author,r_Price,_sim_score
0,0,12,0,Steve Jobs,Walter Isaacson,$12.27,Steve Jobs: A Biography,Walter Isaacson,$29.00,0.370370
1,1,23,0,Becoming Steve Jobs: The Evolution of a Reckless Upstart into a Visionary Leader,Brent Schlender# Rick Tetzeli,,Steve Jobs: A Biography,Walter Isaacson,$29.00,0.105263
2,2,170,0,Steve Jobs,W. Isaacson# Walter Isaacson,$25.04,Steve Jobs: A Biography,Walter Isaacson,$29.00,0.370370
3,3,360,0,The Ultimate Field Guide to Photography,National Geographic,NaN,Steve Jobs: A Biography,Walter Isaacson,$29.00,0.118644
4,4,457,0,Digital Photography: A Basic Manual,Henry Horenstein,$21.46,Steve Jobs: A Biography,Walter Isaacson,$29.00,0.148148
...,...,...,...,...,...,...,...,...,...,...
2196369,2196369,8581,8509,The Best Free Ebook,Alan Smith,NaN,The BlackHat Way,Frederic Haddad,$4.99,0.142857
2196370,2196370,8713,8509,Black Hat SEO For Beginners,Lou Diamond,NaN,The BlackHat Way,Frederic Haddad,$4.99,0.116279
2196371,2196371,9001,8509,The Affliliate Marketing Blueprint,Brandon Olson,NaN,The BlackHat Way,Frederic Haddad,$4.99,0.100000
2196372,2196372,9681,8509,The Boost C++ Libraries,Boris Schäling,,The BlackHat Way,Frederic Haddad,$4.99,0.128205
2196373,2196373,9786,8509,The Watson Dynasty,Richard S. Tedlow,,The BlackHat Way,Frederic Haddad,$4.99,0.147059